//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFront.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coffee
    {
        public int CoffeeID { get; set; }
        public string CoffeeName { get; set; }
        public int TypeID { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public int CoffeeStatusID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string Images { get; set; }
        public string Country { get; set; }
        public string Region { get; set; }
    
        public virtual CoffeeStatu CoffeeStatu { get; set; }
        public virtual CoffeeSupplier CoffeeSupplier { get; set; }
        public virtual CoffeeType CoffeeType { get; set; }
    }
}
